# Generated by Django 5.2.12 on 2026-04-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskresearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.AddField(
            model_name='post',
            name='rental',
            field=models.IntegerField(blank=True, choices=[(1, 'AVAILABLE'), (2, 'UNAVAILABLE')], null=True),
        ),
    ]
