# Generated by Django 5.2.12 on 2026-04-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskresearch', '0002_remove_post_language_post_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('record_text', models.IntegerField(blank=True, choices=[(1, 'RENTED'), (2, 'RETURNED'), (3, 'OVERDUE')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deskresearch.post')),
            ],
        ),
    ]
