# Generated by Django 5.2.12 on 2026-04-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskresearch', '0003_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='deskresearch.post'),
        ),
    ]
