# Generated by Django 5.2.12 on 2026-05-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskresearch', '0004_alter_record_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photo'),
        ),
    ]
