# Generated by Django 5.2.12 on 2026-04-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskresearch', '0003_hashtag_post_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photo'),
        ),
    ]
